### ISSUE TITLE
Adding collaborators

### ISSUE THREAD

**Issue by orgvueelno** [GitbookIO/feedback#156]
I've added collaborators including myself for testing. The book setting updates fine but I haven't got an invitation.

**Comment by SamyPesse** [comment]
It should be fixed now, they will receive an email like:
![screen shot 2016-09-02 at 12 46 10](https://cloud.githubusercontent.com/assets/845425/18201588/5810fa56-710b-11e6-81d5-5502c80e8565.png)

**Comment by orgvueelno** [comment]
No it still doesn't send an invitation. I believe the email is sent when hitting Save after entering email address. A related question is why the default permission is write ? Moreover it is tricky you have to do it in 3 steps: 1) add email 2) hit Save to be able to 3) change permission for an added account. I remember the workflow for this was simpler

**Comment by SamyPesse** [comment]
You still need to click "Save".

We are working on an improvement to highlight the "Save" button when there is changes in the format that requires a save.

The default permission is write, since most of the users want to add collaborators that can edit the books.
Yes the workflow is not perfect, We'll do our best to improve it.

**Comment by orgvueelno** [comment]
Hmmm it doesn't send an email .. still

**Comment by orgvueelno** [comment]
It doesn't send an invitation/ notification email still. But it does give an access.
